# -*- coding: utf-8 -*-
"""cancerapp.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-Tl_hURWE0izqe5UUGBzATdT-fPC9o8
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import numpy as np
# 
# # NOTE: These files are not found in the current environment.
# # Please provide 'best_model.pkl' and 'scaler.pkl' or create dummy ones.
# # For demonstration, I will create dummy files.
# # model = pickle.load(open('best_model.pkl', 'rb'))
# # scaler = pickle.load(open('scaler.pkl', 'rb'))
# 
# # Dummy model and scaler for demonstration if actual files are not present
# # In a real scenario, you would replace these with your trained model and scaler.
# class DummyModel:
#     def predict_proba(self, X):
#         # Simulate a probability prediction
#         # For simplicity, let's say risk is higher if age > 40 and num_partners > 5
#         risk = np.array([0.1]) # Default low risk
#         if X[0, 0] > 40 and X[0, 1] > 5:
#             risk = np.array([0.8]) # Higher risk
#         return np.array([[1 - risk[0], risk[0]]]) # Return probabilities for no-risk and risk
# 
# class DummyScaler:
#     def transform(self, X):
#         return X # Does not scale for dummy purposes
# 
# model = DummyModel()
# scaler = DummyScaler()
# 
# def process_inputs(age, num_partners, first_sex, pregnancies, smokes, hormonal_contraceptives):
#     # Example of how you might convert inputs to numerical features
#     smokes_val = 1 if smokes == "Yes" else 0
#     hormonal_contraceptives_val = 1 if hormonal_contraceptives == "Yes" else 0
# 
#     # In a real application, you would scale these features
#     features = np.array([[age, num_partners, first_sex, pregnancies, smokes_val, hormonal_contraceptives_val]])
# 
#     # Assuming scaler transforms the features
#     scaled_features = scaler.transform(features)
#     return scaled_features
# 
# def predict_risk(features):
#     # Assuming your model returns probabilities for two classes (e.g., [no_risk_proba, risk_proba])
#     probabilities = model.predict_proba(features)[0]
#     risk_proba = probabilities[1] # Probability of being high risk
# 
#     # Determine risk score based on a threshold (e.g., 0.5)
#     risk_score = 1 if risk_proba > 0.5 else 0
# 
#     return risk_score, risk_proba
# 
# def main():
#     st.title("🩺 Cervical Cancer Risk Assessment Tool")
#     st.write("A clinical decision support system for healthcare providers")
# 
#     # Patient input form
#     with st.form("patient_form"):
#         col1, col2 = st.columns(2)
# 
#         with col1:
#             age = st.slider("Age", 15, 80, 35)
#             num_partners = st.slider("Number of sexual partners", 1, 30, 3)
#             first_sex = st.slider("Age at first intercourse", 10, 30, 17)
# 
#         with col2:
#             pregnancies = st.slider("Number of pregnancies", 0, 15, 2)
#             smokes = st.selectbox("Smokes", ["No", "Yes"])
#             hormonal_contraceptives = st.selectbox("Uses hormonal contraceptives", ["No", "Yes"])
# 
#         submitted = st.form_submit_button("Assess Risk")
# 
#         if submitted:
#             # Process inputs and make prediction
#             features = process_inputs(age, num_partners, first_sex, pregnancies, smokes, hormonal_contraceptives)
#             risk_score, confidence = predict_risk(features)
# 
#             # Display results
#             if risk_score == 1:
#                 st.error(f"🚨 HIGH RISK: {confidence:.1%} probability")
#                 st.write("**Recommendation**: Schedule biopsy within 2 weeks")
#             else:
#                 st.success(f"✅ LOW RISK: {(1-confidence):.1%} confidence")
#                 st.write("**Recommendation**: Routine screening schedule")
# 
# if __name__ == "__main__":
#     main()

from ngrok import ngrok

# Get your ngrok authentication token from https://dashboard.ngrok.com/get-started/your-authtoken
# For security, avoid hardcoding your token directly in the notebook.
# A safer way is to store it as a Colab Secret or enter it interactively.
NGROK_AUTH_TOKEN = input("Please enter your ngrok authentication token: ")

# Authenticate ngrok
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Open a tunnel to port 8501 (where Streamlit usually runs)
public_url = ngrok.connect(8501)
print(f"Streamlit App running at: {public_url}")

!pip install ngrok

!streamlit run app.py &>/dev/null& # Run Streamlit in the background

!pip install streamlit

"""To install a Python library, you can use the `pip install` command in a code cell. For example, to install the `requests` library, you would run the following code:"""

!pip install requests

"""The exclamation mark `!` at the beginning of the command tells Colab to run it as a shell command. After installation, you can import and use the library in your Python code."""