# -*- coding: utf-8 -*-
"""Streamlitcancerapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j1etHdLVs9XKuBZHDEGPqsV17hw2sYP

Streamlit code
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import numpy as np
# 
# def main():
#     st.title("🩺 Cervical Cancer Risk Assessment Tool")
#     st.write("A clinical decision support system for healthcare providers")
# 
#     # Patient input form
#     with st.form("patient_form"):
#         col1, col2 = st.columns(2)
# 
#         with col1:
#             age = st.slider("Age", 15, 80, 35)
#             num_partners = st.slider("Number of sexual partners", 1, 30, 3)
#             first_sex = st.slider("Age at first intercourse", 10, 30, 17)
# 
#         with col2:
#             pregnancies = st.slider("Number of pregnancies", 0, 15, 2)
#             smokes = st.selectbox("Smokes", ["No", "Yes"])
#             hormonal_contraceptives = st.selectbox("Uses hormonal contraceptives", ["No", "Yes"])
# 
#         submitted = st.form_submit_button("Assess Risk")
# 
#         if submitted:
#             # Process inputs and make prediction
#             # Load the model and scaler inside the main function to ensure they are available
#             # when the Streamlit app runs in a separate process
#             try:
#                 model = pickle.load(open('best_model.pkl', 'rb'))
#                 scaler = pickle.load(open('scaler.pkl', 'rb'))
#             except FileNotFoundError:
#                 st.error("Error: Model or scaler files not found. Please ensure 'best_model.pkl' and 'scaler.pkl' are in the current directory.")
#                 return
# 
#             # Define feature names based on X_imputed columns used during training
#             # This is a placeholder; in a real app, you'd load these from a config or recreate them
#             feature_names = [
#                 'Age', 'Number of sexual partners', 'First sexual intercourse',
#                 'Num of pregnancies', 'Smokes', 'Smokes (years)', 'Smokes (packs/year)',
#                 'Hormonal Contraceptives', 'Hormonal Contraceptives (years)', 'IUD',
#                 'IUD (years)', 'STDs', 'STDs (number)', 'STDs:condylomatosis',
#                 'STDs:cervical condylomatosis', 'STDs:vaginal condylomatosis',
#                 'STDs:vulvo-perineal condylomatosis', 'STDs:syphilis',
#                 'STDs:pelvic inflammatory disease', 'STDs:genital herpes',
#                 'STDs:molluscum contagiosum', 'STDs:AIDS', 'STDs:HIV',
#                 'STDs:Hepatitis B', 'STDs:HPV', 'STDs: Number of diagnosis',
#                 'Dx:Cancer', 'Dx:CIN', 'Dx:HPV', 'Dx', 'Hinselmann', 'Schiller', 'Citology'
#             ]
# 
#             patient_data = {
#                 'Age': age,
#                 'Number of sexual partners': num_partners,
#                 'First sexual intercourse': first_sex,
#                 'Num of pregnancies': pregnancies,
#                 'Smokes': 1 if smokes == "Yes" else 0,
#                 'Hormonal Contraceptives': 1 if hormonal_contraceptives == "Yes" else 0
#             }
# 
#             # Fill in missing features with default values (e.g., 0 or mean/median from training)
#             # This step is crucial to match the input shape of the trained model.
#             # For a robust app, these defaults should come from the training data statistics.
#             full_patient_data = {}
#             for feature in feature_names:
#                 full_patient_data[feature] = patient_data.get(feature, 0) # Default to 0 if not provided
# 
#             patient_df = pd.DataFrame([full_patient_data])
#             patient_df = patient_df[feature_names] # Ensure correct order of columns
# 
#             # Scale the data
#             patient_scaled = scaler.transform(patient_df)
# 
#             # Make prediction
#             prediction = model.predict(patient_scaled)[0]
#             probability = model.predict_proba(patient_scaled)[0, 1]
# 
#             risk_score = prediction
#             confidence = probability if prediction == 1 else (1 - probability)
# 
#             # Display results
#             if risk_score == 1:
#                 st.error(f"🚨 HIGH RISK: {confidence:.1%} probability")
#                 st.write("**Recommendation**: Schedule biopsy within 2 weeks")
#             else:
#                 st.success(f"✅ LOW RISK: {(1-confidence):.1%} confidence")
#                 st.write("**Recommendation**: Routine screening schedule")
# 
# 
# if __name__ == "__main__":
#     main()